# Generated by Django 5.1.7 on 2025-04-30 03:07

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date_close', models.DateTimeField(verbose_name='Fecha de Cierre')),
                ('count', models.PositiveIntegerField(verbose_name='Cantidad de ventas')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto total en ventas')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_user', to=settings.AUTH_USER_MODEL, verbose_name='cajero')),
            ],
            options={
                'verbose_name': 'Cierre Caja',
                'verbose_name_plural': 'Cirres de Caja',
            },
        ),
    ]
