# Generated by Django 5.2 on 2025-07-22 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_sale_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
