# Generated by Django 5.1.7 on 2025-10-01 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_sale_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshop',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
