# Generated by Django 5.1.7 on 2025-10-03 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_carshop_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshop',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
