# Generated by Django 5.1.7 on 2025-10-11 03:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0006_carshop_user_alter_carshop_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carshop',
            name='count',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad solicitada (permite decimales)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='sale',
            name='count',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='saledetail',
            name='count',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
