# Generated by Django 5.1.7 on 2025-10-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_alter_category_options_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='Código de barras'),
        ),
    ]
