# Generated by Django 5.1.7 on 2025-10-11 03:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_alter_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='count',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad disponible en stock (permite decimales, ej. 1.5 kg)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='num_sale',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad total vendida (permite decimales)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Precio de compra unitario', max_digits=10),
        ),
    ]
