# Generated by Django 5.1.7 on 2025-10-14 01:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_alter_product_count_alter_product_num_sale_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('count', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad disponible en este lote (permite decimales, ej. 1.5 kg)', max_digits=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, help_text='Precio de compra del lote', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='producto.product')),
            ],
            options={
                'ordering': ['expiration_date'],
            },
        ),
    ]
