# Generated by Django 5.1.7 on 2025-10-14 01:18

from django.db import migrations, models
from decimal import Decimal
from django.utils import timezone

def crear_lotes_para_productos_existentes(apps, schema_editor):
    Product = apps.get_model('producto', 'Product')
    Lote = apps.get_model('producto', 'Lote')

    for producto in Product.objects.all():
        # Si el producto tiene stock o fecha de vencimiento anterior
        if producto.count > 0 or producto.due_date:
            Lote.objects.create(
                product=producto,
                expiration_date=producto.due_date,
                count=producto.count or Decimal('0.00'),
                purchase_price=producto.purchase_price,
                created_at=timezone.now()
            )

            # Opcional: reseteamos el campo due_date del producto
            producto.due_date = None
            producto.save(update_fields=['due_date'])

def revertir_creacion_lotes(apps, schema_editor):
    Lote = apps.get_model('producto', 'Lote')
    Lote.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_lote'),  # asegúrate de que coincide con tu última migración real
    ]

    operations = [
        migrations.RunPython(crear_lotes_para_productos_existentes, revertir_creacion_lotes),
    ]
