# Generated by Django 5.1.7 on 2025-10-14 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_auto_20251013_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='due_date',
        ),
    ]
