# Generated by Django 5.1.7 on 2026-06-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0008_remove_product_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.DeleteModel(
            name='Lote',
        ),
    ]
